### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by fkohrt**

### CODE REVIEW

**Comment by Polkas** [comment]
Thanks:) If you want to merge that please update the DESCRIPTION file version to 0.5.1.9000 and add empty # pacs 0.5.1.9000 at the top of the NEWS file.

**Comment by Polkas** [comment]
Unfortunately https://tinyverse.netlify.app/ stops working. When I will confirm it will be not anymore supported then I have to make a bigger update to the vignette.

**Comment by Polkas** [comment]
FYI There is a shiny app with pacs implementation now. https://polkas.shinyapps.io/rdevdash/

**Comment by fkohrt** [comment]
> Unfortunately https://tinyverse.netlify.app/ stops working.

How do you know? For me the site is still working...?

**Comment by fkohrt** [comment]
> Thanks:) If you want to merge that please update the DESCRIPTION file version to 0.5.1.9000 and add empty # pacs 0.5.1.9000 at the top of the NEWS file.

Done :)

**Comment by Polkas** [comment]
> > Unfortunately https://tinyverse.netlify.app/ stops working.
> 
> How do you know? For me the site is still working...?

e.g. https://tinyverse.netlify.com/badge/dplyr is now  https://tinyverse.netlify.app/badge/dplyr :)

**Comment by Polkas** [comment]
Thank you so much for your contribution. Please feel free to colabo more if you want.
The vignette looks good now:)
https://polkas.github.io/pacs/articles/tinyverse.html

**Pull request merged**
